image: java:8-jdk

stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

lint:
  stage: build
  script:
    - ./gradlew ktlintCheck

testJvm:
  stage: test
  script:
    - ./gradlew jvmTest
  only:
    - master

testLinux:
  stage: test
  script:
    - ./gradlew linuxTest
  only:
    - master